/**
 * Tipos y datos mock para el prototipo de Tienda y Servicios.
 * Sin conexión a BD ni al sistema kiosk.
 * Productos de Medicina Regenerativa con imágenes reales.
 */

// Importar imágenes de productos reales
import AliviumImg from '../assets/products/Alivium.jpg';
import AquamineralesImg from '../assets/products/aquaminerales_Mesa_de_trabajo_1_copia_6.jpg';
import NanoCobreImg from '../assets/products/ionescobre_Mesa_de_trabajo_1.jpg';
import NanoExomImg from '../assets/products/Nano-exom.jpg';
import SalesImg from '../assets/products/Sales.jpg';
import Shot5Img from '../assets/products/Shot5-1.jpg';

export type ItemType = 'product' | 'service';

export interface StoreProduct {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  image?: string;
  description: string;
  stock: number;
  category: string;
  categoryId: string; // ID de categoría de Renova Clinic
  type: 'product';
}

export interface StoreCategory {
  id: string;
  name: string;
  icon?: string; // Icono para la categoría
}

export interface StoreCoupon {
  code: string;
  discountPercent: number;
}

export interface Service {
  id: number;
  name: string;
  price: number;
  image?: string;
  description: string;
  duration: number;
  availableDays: string[];
  timeSlots: string[];
  categoryId: string; // ID de categoría de Renova Clinic
  type: 'service';
}

// Tipo unificado para productos y servicios
export type StoreItem = StoreProduct | Service;

/** Cupones de ejemplo: CAMSA10 (10%), CAMSA20 (20%) */
export const MOCK_COUPONS: StoreCoupon[] = [
  { code: 'CAMSA10', discountPercent: 10 },
  { code: 'CAMSA20', discountPercent: 20 },
];

export const MOCK_PRODUCTS: StoreProduct[] = [
  // PRODUCTOS REALES DE RENOVA CLINIC (1-6)
  {
    id: 1,
    name: 'Alivium',
    price: 899.00,
    originalPrice: 1099.00,
    image: AliviumImg,
    description: 'Suplemento regenerativo avanzado para alivio y regeneración celular profunda.',
    stock: 45,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 2,
    name: 'Aquaminerales',
    price: 1299.00,
    image: AquamineralesImg,
    description: 'Minerales marinos esenciales para regeneración y salud celular óptima.',
    stock: 32,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 3,
    name: 'Nano Partículas de Cobre',
    price: 1599.00,
    originalPrice: 1899.00,
    image: NanoCobreImg,
    description: 'Nanopartículas de cobre para regeneración celular avanzada y anti-envejecimiento.',
    stock: 28,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 4,
    name: 'NanoExom',
    price: 1199.00,
    image: NanoExomImg,
    description: 'Tecnología de exosomas en nanopartículas para regeneración celular profunda y rejuvenecimiento.',
    stock: 40,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 5,
    name: 'Sales Regenerativas',
    price: 1099.00,
    image: SalesImg,
    description: 'Sales minerales esenciales para equilibrio y regeneración del organismo.',
    stock: 55,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 6,
    name: 'Shot 5',
    price: 1899.00,
    image: Shot5Img,
    description: 'Complejo regenerativo premium con 5 componentes activos para máxima eficacia celular.',
    stock: 20,
    category: 'Suplementos',
    categoryId: 'suplementos',
    type: 'product',
  },
  
  // SUPLEMENTOS - COLÁGENO Y PÉPTIDOS (7-16)
  {
    id: 7,
    name: 'Péptidos de Colágeno Hidrolizado 300g',
    price: 899.00,
    originalPrice: 1099.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Colágeno hidrolizado tipo I y III. Favorece la regeneración de tejidos, piel, cabello y uñas.',
    stock: 45,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 8,
    name: 'Colágeno Marino con Vitamina C 500g',
    price: 1299.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Colágeno de pescado de alta pureza. Mejora elasticidad cutánea y regeneración celular.',
    stock: 32,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 9,
    name: 'Colágeno Bovino Fortigel 7g',
    price: 1599.00,
    originalPrice: 1899.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Péptidos de colágeno bioactivos. Regeneración articular y cartilaginosa comprobada.',
    stock: 28,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 10,
    name: 'Colágeno con Ácido Hialurónico 250g',
    price: 1199.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Fórmula sinérgica para regeneración dérmica y articular. Hidratación profunda.',
    stock: 40,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 11,
    name: 'Péptidos de Colágeno Sabor Vainilla 454g',
    price: 1099.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Colágeno hidrolizado en polvo. Fácil de disolver. Sabor natural a vainilla.',
    stock: 55,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 12,
    name: 'Colágeno Tipo II No Desnaturalizado 60 cápsulas',
    price: 1399.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Colágeno específico para regeneración cartilaginosa. Protege articulaciones.',
    stock: 38,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 13,
    name: 'Péptidos de Colágeno con Magnesio 300g',
    price: 999.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Combinación regenerativa. Magnesio para síntesis proteica y función muscular.',
    stock: 42,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 14,
    name: 'Colágeno Vegano de Algas Marinas 200g',
    price: 1499.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Alternativa vegetal rica en aminoácidos regenerativos. Ideal para veganos.',
    stock: 25,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 15,
    name: 'Colágeno Líquido con Coenzima Q10 500ml',
    price: 1699.00,
    originalPrice: 1999.00,
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Fórmula líquida de rápida absorción. Energía celular y regeneración cutánea.',
    stock: 30,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 16,
    name: 'Péptidos de Colágeno Premium 500g',
    price: 1899.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Máxima pureza y biodisponibilidad. Regeneración acelerada de tejidos.',
    stock: 20,
    category: 'Colágeno y Péptidos',
    categoryId: 'suplementos',
    type: 'product',
  },

  // SUPLEMENTOS ARTICULARES (17-26)
  {
    id: 17,
    name: 'Glucosamina + Condroitina + MSM 120 cápsulas',
    price: 799.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Trío regenerativo articular. Repara cartílago y reduce inflamación.',
    stock: 50,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 18,
    name: 'Ácido Hialurónico Oral 100mg 60 cápsulas',
    price: 1299.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Hidratación profunda desde dentro. Regenera tejidos y mejora movilidad articular.',
    stock: 35,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 19,
    name: 'Cúrcuma Curcumina 95% 90 cápsulas',
    price: 699.00,
    originalPrice: 899.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Antiinflamatorio natural. Protege articulaciones y acelera regeneración.',
    stock: 60,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 20,
    name: 'Boswellia Serrata Extracto 60 cápsulas',
    price: 899.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración articular natural. Reduce dolor y mejora flexibilidad.',
    stock: 40,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 21,
    name: 'MSM (Metilsulfonilmetano) 1000mg 120 cápsulas',
    price: 599.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Azufre orgánico para regeneración de tejidos conectivos y cartílago.',
    stock: 55,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 22,
    name: 'Condroitina Sulfato 800mg 90 cápsulas',
    price: 1099.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Componente esencial del cartílago. Regenera y protege articulaciones.',
    stock: 33,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 23,
    name: 'Glucosamina Sulfato 1500mg 120 cápsulas',
    price: 799.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Precursor del cartílago. Repara y mantiene salud articular.',
    stock: 48,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 24,
    name: 'Complejo Articular Premium 180 cápsulas',
    price: 1499.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Fórmula completa: colágeno, glucosamina, condroitina, MSM, cúrcuma.',
    stock: 28,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 19,
    name: 'Ácido Hialurónico + Colágeno Articular 90 cápsulas',
    price: 1399.00,
    originalPrice: 1699.00,
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Sinergia regenerativa. Lubrica y regenera articulaciones desde dentro.',
    stock: 36,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 26,
    name: 'Gelatina Hidrolizada para Articulaciones 500g',
    price: 699.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Gelatina rica en colágeno. Regeneración natural de cartílago y tendones.',
    stock: 45,
    category: 'Suplementos Articulares',
    categoryId: 'suplementos',
    type: 'product',
  },

  // ANTIOXIDANTES Y ANTI-ENVEJECIMIENTO (27-36)
  {
    id: 27,
    name: 'Resveratrol 500mg 60 cápsulas',
    price: 1199.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Antioxidante potente. Activa genes de longevidad y regeneración celular.',
    stock: 42,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 28,
    name: 'Coenzima Q10 200mg 60 cápsulas',
    price: 999.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Energía mitocondrial. Regenera células y protege del envejecimiento.',
    stock: 50,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 29,
    name: 'NMN (Nicotinamida Mononucleótido) 500mg 60 cápsulas',
    price: 2499.00,
    originalPrice: 2999.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Precursor de NAD+. Revierte envejecimiento celular y regenera ADN.',
    stock: 18,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 30,
    name: 'Astaxantina 12mg 60 cápsulas',
    price: 1399.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Antioxidante más potente. Protege piel y ojos. Regeneración celular.',
    stock: 35,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 25,
    name: 'Ácido Alfa Lipoico 600mg 60 cápsulas',
    price: 899.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Antioxidante universal. Regenera otros antioxidantes y protege nervios.',
    stock: 48,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 32,
    name: 'NAC (N-Acetilcisteína) 600mg 120 cápsulas',
    price: 799.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Precursor de glutatión. Desintoxica y regenera células hepáticas.',
    stock: 52,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 33,
    name: 'Pterostilbeno 100mg 60 cápsulas',
    price: 1599.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Resveratrol mejorado. Mayor biodisponibilidad. Regeneración celular avanzada.',
    stock: 25,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 34,
    name: 'Spermidina 10mg 60 cápsulas',
    price: 1899.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Autofagia celular. Elimina células viejas y regenera tejidos.',
    stock: 22,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 35,
    name: 'Fisetina 100mg 60 cápsulas',
    price: 1299.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Flavonoide senolítico. Elimina células senescentes y regenera.',
    stock: 30,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 36,
    name: 'Complejo Antioxidante Premium 90 cápsulas',
    price: 1499.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Mezcla sinérgica: Q10, resveratrol, astaxantina, ácido alfa lipoico.',
    stock: 38,
    category: 'Antioxidantes',
    categoryId: 'suplementos',
    type: 'product',
  },

  // SÉRUMS Y TRATAMIENTOS TÓPICOS (37-46)
  {
    id: 37,
    name: 'Sérum Regenerador Premium',
    price: 189.00,
    originalPrice: 219.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Sérum concentrado con factores de crecimiento y péptidos bioactivos para regeneración celular avanzada.',
    stock: 28,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 38,
    name: 'Sérum de Ácido Hialurónico Puro 50ml',
    price: 1299.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Hidratación profunda. Regenera y rellena arrugas desde dentro.',
    stock: 40,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 39,
    name: 'Sérum de Retinol 1% 30ml',
    price: 1599.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración celular acelerada. Renueva piel y reduce signos de edad.',
    stock: 32,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 40,
    name: 'Sérum de Factores de Crecimiento 30ml',
    price: 2499.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Tecnología regenerativa avanzada. Estimula producción de colágeno endógeno.',
    stock: 15,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 41,
    name: 'Sérum de Vitamina C Esterificada 30ml',
    price: 1199.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Antioxidante tópico. Ilumina, regenera y protege del daño solar.',
    stock: 45,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 42,
    name: 'Sérum de Niacinamida 10% 50ml',
    price: 999.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regenera barrera cutánea. Reduce poros y mejora textura de la piel.',
    stock: 50,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 43,
    name: 'Sérum de Péptidos Multi-Función 30ml',
    price: 1699.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Complejo de péptidos bioactivos. Regeneración y firmeza cutánea.',
    stock: 35,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 44,
    name: 'Sérum de Ácido Glicólico 10% 50ml',
    price: 1099.00,
    originalPrice: 1399.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Exfoliación química suave. Renueva y regenera capas superficiales.',
    stock: 42,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 45,
    name: 'Sérum de Stem Cells Vegetales 30ml',
    price: 1999.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Células madre vegetales. Regeneración profunda y protección celular.',
    stock: 25,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 46,
    name: 'Sérum Regenerativo Nocturno 50ml',
    price: 1799.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Fórmula nocturna intensiva. Regenera mientras duermes.',
    stock: 30,
    category: 'Sérums y Tratamientos',
    categoryId: 'cuidado-casa',
    type: 'product',
  },

  // PRODUCTOS CAPILARES (47-51)
  {
    id: 47,
    name: 'Sérum Capilar con Péptidos 100ml',
    price: 1499.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración folicular. Fortalece raíz y estimula crecimiento.',
    stock: 38,
    category: 'Productos Capilares',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 48,
    name: 'Shampoo Regenerativo con Colágeno 250ml',
    price: 799.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Limpieza regenerativa. Fortalece y repara cabello dañado.',
    stock: 55,
    category: 'Productos Capilares',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 49,
    name: 'Tratamiento Capilar con Biotina 200ml',
    price: 1199.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración capilar intensiva. Espesamiento y crecimiento acelerado.',
    stock: 40,
    category: 'Productos Capilares',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 50,
    name: 'Ampollas Regenerativas Capilares 10x10ml',
    price: 1699.00,
    originalPrice: 1999.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Tratamiento intensivo. Péptidos, factores de crecimiento y nutrientes.',
    stock: 28,
    category: 'Productos Capilares',
    categoryId: 'cuidado-casa',
    type: 'product',
  },
  {
    id: 51,
    name: 'Mascarilla Capilar Regenerativa 300ml',
    price: 999.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Hidratación y reparación profunda. Restaura cabello desde la raíz.',
    stock: 45,
    category: 'Productos Capilares',
    categoryId: 'cuidado-casa',
    type: 'product',
  },

  // SUPLEMENTOS NUTRICIONALES REGENERATIVOS (52-61)
  {
    id: 52,
    name: 'Omega-3 EPA/DHA 1000mg 120 cápsulas',
    price: 899.00,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Ácidos grasos esenciales. Antiinflamatorio y regeneración celular.',
    stock: 60,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 47,
    name: 'Magnesio Glicinato 400mg 120 cápsulas',
    price: 699.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Mineral esencial para síntesis proteica y regeneración muscular.',
    stock: 65,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 54,
    name: 'Zinc Quelado 30mg 90 cápsulas',
    price: 599.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Inmune y regeneración. Cicatrización y síntesis de colágeno.',
    stock: 58,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 55,
    name: 'Vitamina D3 + K2 5000 UI 120 cápsulas',
    price: 799.00,
    originalPrice: 999.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración ósea y celular. Absorción de calcio optimizada.',
    stock: 52,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 56,
    name: 'Probióticos Regenerativos 50 billones CFU 60 cápsulas',
    price: 1299.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Cepas específicas para regeneración intestinal y salud sistémica.',
    stock: 42,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 57,
    name: 'L-Glutamina 1000mg 120 cápsulas',
    price: 899.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Aminoácido regenerativo. Repara intestino y músculo.',
    stock: 48,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 52,
    name: 'B-Complejo Regenerativo 90 cápsulas',
    price: 799.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Coenzimas para energía celular y regeneración de tejidos.',
    stock: 55,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 59,
    name: 'Creatina Monohidratada 500g',
    price: 999.00,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Regeneración muscular y energía celular. Reparación post-ejercicio.',
    stock: 40,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 60,
    name: 'BCAA Regenerativos 2:1:1 300g',
    price: 1199.00,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Aminoácidos ramificados. Recuperación y regeneración muscular acelerada.',
    stock: 35,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
  {
    id: 61,
    name: 'Complejo Regenerativo Premium 180 cápsulas',
    price: 1999.00,
    originalPrice: 2499.00,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80&auto=format',
    description: 'Fórmula completa: colágeno, Q10, resveratrol, vitaminas, minerales.',
    stock: 22,
    category: 'Suplementos Nutricionales',
    categoryId: 'suplementos',
    type: 'product',
  },
];

export const MOCK_CATEGORIES: StoreCategory[] = [
  { id: 'all', name: 'Todos', icon: '▦' },
  { id: 'facial', name: 'Tratamientos Faciales', icon: '✨' },
  { id: 'corporal', name: 'Tratamientos Corporales', icon: '❤️' },
  { id: 'suplementos', name: 'Suplementos', icon: '🔗' },
  { id: 'cuidado-casa', name: 'Cuidado en Casa', icon: '🏠' },
];

/** Días en formato corto para CalendarPicker (Lun, Mar, Mié, Jue, Vie, Sáb) */
export const MOCK_SERVICES: Service[] = [
  {
    id: 1,
    name: 'Tratamiento PRP Facial',
    price: 450.0,
    description: 'Sesión de plasma rico en plaquetas para rejuvenecimiento facial y regeneración celular.',
    duration: 60,
    availableDays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'],
    timeSlots: ['9:00', '10:00', '11:00', '14:00', '15:00', '16:00'],
    categoryId: 'facial',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=500&h=500&fit=crop&q=80&auto=format',
  },
  {
    id: 2,
    name: 'Mesoterapia Corporal',
    price: 320.0,
    description: 'Tratamiento de mesoterapia para reducción de celulitis y reafirmación de la piel.',
    duration: 45,
    availableDays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'],
    timeSlots: ['9:00', '10:30', '12:00', '14:00', '15:30', '16:00'],
    categoryId: 'corporal',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=500&h=500&fit=crop&q=80&auto=format',
  },
  {
    id: 3,
    name: 'Peeling Regenerativo',
    price: 180.0,
    description: 'Peeling químico con ácidos orgánicos para renovación celular y mejora de la textura.',
    duration: 30,
    availableDays: ['Lun', 'Mié', 'Vie'],
    timeSlots: ['9:00', '10:00', '11:00', '14:00', '15:00'],
    categoryId: 'facial',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&h=500&fit=crop&q=80&auto=format',
  },
  {
    id: 4,
    name: 'Radiofrecuencia Facial',
    price: 250.0,
    description: 'Sesión de radiofrecuencia para tensado y rejuvenecimiento facial no invasivo.',
    duration: 45,
    availableDays: ['Mar', 'Jue', 'Sáb'],
    timeSlots: ['9:00', '10:30', '12:00', '14:00', '15:30'],
    categoryId: 'facial',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=500&h=500&fit=crop&q=80&auto=format',
  },
  {
    id: 5,
    name: 'Terapia con Células Madre',
    price: 1200.0,
    description: 'Tratamiento avanzado con células madre para regeneración profunda y rejuvenecimiento.',
    duration: 90,
    availableDays: ['Lun', 'Mié', 'Vie'],
    timeSlots: ['9:00', '11:00', '14:00', '16:00'],
    categoryId: 'corporal',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=500&h=500&fit=crop&q=80&auto=format',
  },
  {
    id: 6,
    name: 'Carboxiterapia Corporal',
    price: 220.0,
    description: 'Tratamiento con dióxido de carbono para mejorar circulación y reducir grasa localizada.',
    duration: 30,
    availableDays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'],
    timeSlots: ['9:00', '10:00', '11:00', '14:00', '15:00', '16:00'],
    categoryId: 'corporal',
    type: 'service',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&h=500&fit=crop&q=80&auto=format',
  },
];
